name: survey
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_secure_storage:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  http:
  provider:
  equatable:
  get:

dev_dependencies:
  flutter_launcher_icons: "^0.8.0"
  test:
  mockito:
  faker:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - lib/ui/assets/

flutter_icons:
  android: true
  ios: true
  image_path_android: "lib/ui/assets/icon/android.png"
  image_path_ios: "lib/ui/assets/icon/android.png"
  adaptive_icon_background: "lib/ui/assets/icon/background.png"
  adaptive_icon_foreground: "lib/ui/assets/icon/foreground.png"


